import PDFDocument from "pdfkit";

function asArray(value) {
  return Array.isArray(value) ? value : [];
}

function stringify(value) {
  if (value == null) return "";
  if (Array.isArray(value)) return value.map(stringify).join(", ");
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

function section(doc, title, body) {
  doc.moveDown(0.8);
  doc.fillColor("#2E1065").font("Helvetica-Bold").fontSize(16).text(title);
  doc.moveDown(0.25);
  if (Array.isArray(body)) {
    body.filter(Boolean).forEach((item) => {
      doc.fillColor("#111827").font("Helvetica").fontSize(10).text(`- ${stringify(item)}`, { lineGap: 3 });
    });
    return;
  }
  doc.fillColor("#111827").font("Helvetica").fontSize(10).text(stringify(body || "No applicable findings were available for this section."), { lineGap: 3 });
}

function metricGrid(doc, metrics = {}) {
  const rows = [
    ["Total Records", metrics.totalRecords],
    ["Unique Categories", metrics.uniqueCategories],
    ["Countries", metrics.countries],
    ["Sources", metrics.totalSources],
    ["Images", metrics.images],
    ["Charts", metrics.charts],
    ["Confidence Score", `${metrics.confidenceScore || 0}%`],
    ["Dataset Quality", `${metrics.datasetQualityScore || 0}%`],
    ["Duplicates", `${metrics.duplicatePercentage || 0}%`],
    ["Missing Data", `${metrics.missingDataPercentage || 0}%`]
  ];

  rows.forEach(([label, value]) => {
    doc.font("Helvetica-Bold").fontSize(9).fillColor("#4C1D95").text(`${label}: `, { continued: true });
    doc.font("Helvetica").fillColor("#111827").text(stringify(value ?? 0));
  });
}

function addInsightDetails(doc, insights = []) {
  insights.slice(0, 10).forEach((insight, index) => {
    doc.moveDown(0.45);
    doc.font("Helvetica-Bold").fontSize(11).fillColor("#111827").text(`Insight ${index + 1}: ${insight.title || "Analyst insight"}`);
    doc.font("Helvetica").fontSize(9).text(`Observation: ${insight.observation || ""}`);
    doc.text(`Evidence: ${insight.evidence || ""}`);
    doc.text(`Business Impact: ${insight.businessImpact || ""}`);
    doc.text(`Recommendation: ${insight.recommendation || ""}`);
  });
}

function addStatistics(doc, stats = []) {
  if (!stats.length) {
    doc.font("Helvetica").fontSize(10).text("No numeric fields were reliable enough for statistical analysis.");
    return;
  }

  stats.slice(0, 8).forEach((stat) => {
    doc.font("Helvetica-Bold").fontSize(10).fillColor("#111827").text(stat.column);
    doc.font("Helvetica").fontSize(9).text(
      `Mean ${stat.mean}; Median ${stat.median}; Mode ${stat.mode}; Min ${stat.min}; Max ${stat.max}; Std Dev ${stat.standardDeviation}; Variance ${stat.variance}; P25 ${stat.percentile25}; P75 ${stat.percentile75}`
    );
    doc.moveDown(0.25);
  });
}

function addVisuals(doc, visuals = []) {
  visuals.forEach((chart) => {
    doc.font("Helvetica-Bold").fontSize(10).fillColor(chart.applicable ? "#166534" : "#92400E").text(`${chart.type}: ${chart.title}`);
    doc.font("Helvetica").fontSize(9).fillColor("#111827").text(chart.applicable ? chart.reason : `Not applicable: ${chart.reason}`);
    doc.moveDown(0.2);
  });
}

export function generateReportPDF(reportData, dataset) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        bufferPages: true,
        margin: 48,
      });

      const buffers = [];
      const content = reportData.reportContent || {};
      const metrics = content.datasetOverview || reportData.analystProfile?.metrics || reportData.metadata || {};

      doc.on("data", (buffer) => buffers.push(buffer));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      doc.fillColor("#6D28D9").font("Helvetica-Bold").fontSize(28).text(content.coverPage?.reportTitle || reportData.title || "Analyst Research Report", { align: "center" });
      doc.moveDown(0.5);
      doc.fillColor("#111827").font("Helvetica").fontSize(13).text(content.coverPage?.query || reportData.query || dataset?.query || "", { align: "center" });
      doc.moveDown(1);
      doc.fontSize(10).text(`Generated: ${new Date(content.coverPage?.generatedDate || Date.now()).toLocaleString()}`, { align: "center" });
      doc.text(`Workspace: ${content.coverPage?.workspace || dataset?.workspaceName || "Report Workspace"}`, { align: "center" });
      doc.text(`Generated by: ${content.coverPage?.generatedBy || "AI Scraping Agent"}`, { align: "center" });
      doc.text(`Report ID: ${content.coverPage?.reportId || reportData._id || ""}`, { align: "center" });

      doc.addPage();
      section(doc, "Executive Summary", content.executiveSummary);
      section(doc, "Dataset Overview", "");
      metricGrid(doc, metrics);
      section(doc, "Methodology", content.methodology);
      section(doc, "Data Cleaning Summary", Object.entries(content.dataCleaningSummary || {}).map(([key, value]) => `${key}: ${value}`));

      doc.addPage();
      section(doc, "Statistical Analysis", "");
      addStatistics(doc, asArray(content.statisticalAnalysis));
      section(doc, "Trend Analysis", content.trendAnalysis?.summary || "Trend analysis was not applicable to this dataset.");
      section(doc, "Correlation Analysis", asArray(content.correlationAnalysis).map((item) => item.explanation));

      doc.addPage();
      section(doc, "AI Generated Insights", "");
      addInsightDetails(doc, asArray(content.insightDetails));
      section(doc, "Visual Analytics", "");
      addVisuals(doc, asArray(content.visualAnalytics).length ? asArray(content.visualAnalytics) : asArray(reportData.chartSnapshots));

      doc.addPage();
      section(doc, "Geographic Analysis", content.geographicAnalysis?.summary);
      section(doc, "Entity Analysis", content.entityAnalysis?.summary);
      section(doc, "Image Analysis", asArray(content.imageAnalysis).map((image) => `${image.label}: ${image.description} Relevance ${image.relevanceScore}/100.`));
      section(doc, "Source Reliability Analysis", asArray(content.sourceReliabilityAnalysis).map((source) => `${source.domain}: ${source.reliabilityScore}/100. ${source.authority}. ${source.bias}.`));

      doc.addPage();
      section(doc, "Comparative Analysis", content.comparativeAnalysis?.summary);
      section(doc, "AI Recommendations", asArray(content.recommendations).map((item) => `${item.finding} -> ${item.recommendation} Expected impact: ${item.expectedImpact}`));
      section(doc, "Limitations", content.limitations);
      section(doc, "Future Predictions", content.futurePredictions?.summary);
      section(doc, "Conclusion", content.conclusion);

      doc.addPage();
      section(doc, "Appendix A - Complete Data Table", `Rows available in dataset export: ${asArray(dataset?.data).length}`);
      section(doc, "Appendix B - Source List", asArray(dataset?.sourceUrls?.length ? dataset.sourceUrls : dataset?.sources).slice(0, 40));
      section(doc, "Appendix C - Metadata", Object.entries(metrics).map(([key, value]) => `${key}: ${stringify(value)}`));
      section(doc, "Appendix D - Charts", asArray(content.visualAnalytics).map((chart) => `${chart.type}: ${chart.applicable ? "Applicable" : chart.reason}`));
      section(doc, "Appendix E - AI Prompt History", content.appendices?.appendixE || []);
      section(doc, "Appendix F - Dataset Statistics", asArray(content.statisticalAnalysis).map((stat) => `${stat.column}: mean ${stat.mean}, median ${stat.median}, min ${stat.min}, max ${stat.max}`));

      const pages = doc.bufferedPageRange().count;
      for (let i = 0; i < pages; i += 1) {
        doc.switchToPage(i);
        doc.fontSize(8).fillColor("#6B7280").text(`Page ${i + 1} of ${pages}`, 48, doc.page.height - 34, { align: "center" });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
